inherit_from: .rubocop_todo.yml

# This is a config synced from dry-rb/template-gem repo

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - benchmarks/*.rb
    - spec/support/coverage.rb
    - spec/support/warnings.rb
    - spec/support/rspec_options.rb
    - Gemfile.devtools
    - "*.gemspec"

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineLength:
  Max: 100
  Exclude:
    - "spec/**/*.rb"

Lint/AmbiguousBlockAssociation:
  Enabled: true
  # because 'expect { foo }.to change { bar }' is fine
  Exclude:
    - "spec/**/*.rb"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*.rb"

Lint/SuppressedException:
  Exclude:
    - "spec/spec_helper.rb"

Lint/LiteralAsCondition:
  Exclude:
    - "spec/**/*.rb"

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/*-*.rb"

Naming/MethodParameterName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Semicolon:
  Exclude:
    - "spec/**/*.rb"
